version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend/flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/flask:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: soccerpro
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: